cmd_/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dtb := mkdir -p /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/ ; /projects/hnd/tools/bcm/crosstools-arm-gcc-9.2-linux-4.19-glibc-2.30-binutils-2.32/usr/bin/arm-buildroot-linux-gnueabi-gcc -E -Wp,-MD,/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/.96757REF2T.dtb.d.pre.tmp -nostdinc -I./scripts/dtc/include-prefixes -undef -D__DTS__ -x assembler-with-cpp -o /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/.96757REF2T.dtb.dts.tmp /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dts ; ./scripts/dtc/dtc -O dtb -o /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dtb -b 0 -i/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/ -i./scripts/dtc/include-prefixes -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-simple_bus_reg -Wno-unique_unit_address -Wno-pci_device_reg  -d /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/.96757REF2T.dtb.d.dtc.tmp /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/.96757REF2T.dtb.dts.tmp ; cat /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/.96757REF2T.dtb.d.pre.tmp /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/.96757REF2T.dtb.d.dtc.tmp > /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/.96757REF2T.dtb.d

source_/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dtb := /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dts

deps_/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dtb := \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/6756.dtsi \
    $(wildcard include/config/bcm/pdc.h) \
    $(wildcard include/config/bcm/spu.h) \
    $(wildcard include/config/bcm/pcie/hcd.h) \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/linux_autoconf.h \
    $(wildcard include/config/nf/conntrack/h323.h) \
    $(wildcard include/config/netfilter/family/bridge.h) \
    $(wildcard include/config/kernel/gzip.h) \
    $(wildcard include/config/cc/has/sancov/trace/pc.h) \
    $(wildcard include/config/atags.h) \
    $(wildcard include/config/blog/gre.h) \
    $(wildcard include/config/arch/optional/kernel/rwx/default.h) \
    $(wildcard include/config/memory/isolation.h) \
    $(wildcard include/config/slub/cpu/partial.h) \
    $(wildcard include/config/rfs/accel.h) \
    $(wildcard include/config/ip/nf/target/redirect.h) \
    $(wildcard include/config/crc32.h) \
    $(wildcard include/config/default/mptcp/sched.h) \
    $(wildcard include/config/i2c/boardinfo.h) \
    $(wildcard include/config/bcm/dhd/archer.h) \
    $(wildcard include/config/nf/nat/proto/sctp.h) \
    $(wildcard include/config/vfp.h) \
    $(wildcard include/config/sa/fastpath/nat/pptp.h) \
    $(wildcard include/config/aeabi.h) \
    $(wildcard include/config/bcm/kf/wdt.h) \
    $(wildcard include/config/high/res/timers.h) \
    $(wildcard include/config/bcm/kf/ipv6.h) \
    $(wildcard include/config/arch/multi/v6/v7.h) \
    $(wildcard include/config/arch/has/set/memory.h) \
    $(wildcard include/config/vlan/8021q.h) \
    $(wildcard include/config/ip/multiple/tables.h) \
    $(wildcard include/config/uevent/helper.h) \
    $(wildcard include/config/fix/earlycon/mem.h) \
    $(wildcard include/config/inotify/user.h) \
    $(wildcard include/config/bridge/ebt/t/filter.h) \
    $(wildcard include/config/glob.h) \
    $(wildcard include/config/ppp/sync/tty.h) \
    $(wildcard include/config/arch/suspend/possible.h) \
    $(wildcard include/config/bcm/otp/impl.h) \
    $(wildcard include/config/mac80211/sta/hash/max/size.h) \
    $(wildcard include/config/have/arch/mmap/rnd/bits.h) \
    $(wildcard include/config/arm/unwind.h) \
    $(wildcard include/config/tcp/cong/htcp.h) \
    $(wildcard include/config/net/switchdev.h) \
    $(wildcard include/config/ssb/possible.h) \
    $(wildcard include/config/bridge/ebt/t/nat.h) \
    $(wildcard include/config/nf/nat/sip.h) \
    $(wildcard include/config/asymmetric/key/type.h) \
    $(wildcard include/config/mtd/cmdline/parts.h) \
    $(wildcard include/config/ip/nf/nat.h) \
    $(wildcard include/config/bridge/nf/ebtables.h) \
    $(wildcard include/config/usb/ohci/little/endian.h) \
    $(wildcard include/config/net/sch/fifo.h) \
    $(wildcard include/config/fsnotify.h) \
    $(wildcard include/config/blk/dev/loop/min/count.h) \
    $(wildcard include/config/stp.h) \
    $(wildcard include/config/inet6/tunnel.h) \
    $(wildcard include/config/nf/conntrack/sip.h) \
    $(wildcard include/config/crypto/manager/disable/tests.h) \
    $(wildcard include/config/have/kernel/lzma.h) \
    $(wildcard include/config/arch/want/ipc/parse/version.h) \
    $(wildcard include/config/bcm/kf/kbonding.h) \
    $(wildcard include/config/generic/smp/idle/thread.h) \
    $(wildcard include/config/squashfs/file/cache.h) \
    $(wildcard include/config/bcm/kf/printk/int/enabled.h) \
    $(wildcard include/config/bcm/kf/usb/hosts.h) \
    $(wildcard include/config/default/security/dac.h) \
    $(wildcard include/config/ldisc/autoload.h) \
    $(wildcard include/config/fib/rules.h) \
    $(wildcard include/config/bcm/archer.h) \
    $(wildcard include/config/bcm/kf/sched/rt/share.h) \
    $(wildcard include/config/ip6/nf/mangle.h) \
    $(wildcard include/config/bcm/bca/pinctrl.h) \
    $(wildcard include/config/have/irq/time/accounting.h) \
    $(wildcard include/config/arch/has/devmem/is/allowed.h) \
    $(wildcard include/config/ipv6.h) \
    $(wildcard include/config/have/stackprotector.h) \
    $(wildcard include/config/bcm/cfe/xargs/early/size.h) \
    $(wildcard include/config/crypto/aead.h) \
    $(wildcard include/config/magic/sysrq/serial.h) \
    $(wildcard include/config/bql.h) \
    $(wildcard include/config/default/tcp/cong.h) \
    $(wildcard include/config/uevent/helper/path.h) \
    $(wildcard include/config/devtmpfs.h) \
    $(wildcard include/config/bcm/kf/jffs.h) \
    $(wildcard include/config/bcm/wlan/wbd.h) \
    $(wildcard include/config/nf/nat/proto/gre.h) \
    $(wildcard include/config/nf/nat/redirect.h) \
    $(wildcard include/config/hotplug/cpu.h) \
    $(wildcard include/config/bcm/accel.h) \
    $(wildcard include/config/wlan.h) \
    $(wildcard include/config/bcm/kf/proto/esp.h) \
    $(wildcard include/config/bcm/cfe/xargs.h) \
    $(wildcard include/config/have/arm/scu.h) \
    $(wildcard include/config/dhcp/options.h) \
    $(wildcard include/config/bcm/kernel/custom.h) \
    $(wildcard include/config/legacy/ptys.h) \
    $(wildcard include/config/crypto/drbg/menu.h) \
    $(wildcard include/config/crypto/rng2.h) \
    $(wildcard include/config/netfilter/netlink/queue.h) \
    $(wildcard include/config/tun.h) \
    $(wildcard include/config/ipv6/pimsm/v2.h) \
    $(wildcard include/config/behavior/manager.h) \
    $(wildcard include/config/cfg80211.h) \
    $(wildcard include/config/bcm/cpu/arch/name.h) \
    $(wildcard include/config/of/reserved/mem.h) \
    $(wildcard include/config/have/proc/cpu.h) \
    $(wildcard include/config/lzo/decompress.h) \
    $(wildcard include/config/bcm/bca/usb.h) \
    $(wildcard include/config/bcm/chipinfo.h) \
    $(wildcard include/config/crypto/hmac.h) \
    $(wildcard include/config/bcm/enet/impl.h) \
    $(wildcard include/config/bcm/ext/switch.h) \
    $(wildcard include/config/have/dma/contiguous.h) \
    $(wildcard include/config/dql.h) \
    $(wildcard include/config/vxlan.h) \
    $(wildcard include/config/coredump.h) \
    $(wildcard include/config/bcma/possible.h) \
    $(wildcard include/config/nf/log/ipv4.h) \
    $(wildcard include/config/bcm/i2c/chip.h) \
    $(wildcard include/config/bcm/chip/number.h) \
    $(wildcard include/config/force/max/zoneorder.h) \
    $(wildcard include/config/bcm/ca7/smp.h) \
    $(wildcard include/config/nf/tables/arp.h) \
    $(wildcard include/config/modules/use/elf/rel.h) \
    $(wildcard include/config/net/ipgre/demux.h) \
    $(wildcard include/config/printk.h) \
    $(wildcard include/config/bcm/bca/led.h) \
    $(wildcard include/config/timerfd.h) \
    $(wildcard include/config/bcm/vlan/impl.h) \
    $(wildcard include/config/netfilter/xt/target/skiplog.h) \
    $(wildcard include/config/mtd/cfi/i2.h) \
    $(wildcard include/config/crypto/authenc.h) \
    $(wildcard include/config/bcm/kf/emmc.h) \
    $(wildcard include/config/bcm/thermal.h) \
    $(wildcard include/config/sa/fastpath/bridge.h) \
    $(wildcard include/config/mtd.h) \
    $(wildcard include/config/migration.h) \
    $(wildcard include/config/have/arch/jump/label.h) \
    $(wildcard include/config/build/salt.h) \
    $(wildcard include/config/devtmpfs/mount.h) \
    $(wildcard include/config/bcm/kernel/bonding.h) \
    $(wildcard include/config/netfilter/xt/match/blog.h) \
    $(wildcard include/config/generic/net/utils.h) \
    $(wildcard include/config/crypto/des.h) \
    $(wildcard include/config/gpiolib/fastpath/limit.h) \
    $(wildcard include/config/online/ip/by/mac.h) \
    $(wildcard include/config/nls/codepage/437.h) \
    $(wildcard include/config/net/cls/u32.h) \
    $(wildcard include/config/mtd/ubi/wl/threshold.h) \
    $(wildcard include/config/ip/mroute/common.h) \
    $(wildcard include/config/net/ingress.h) \
    $(wildcard include/config/arm/gic.h) \
    $(wildcard include/config/old/sigsuspend3.h) \
    $(wildcard include/config/arch/has/sg/chain.h) \
    $(wildcard include/config/core/dump/default/elf/headers.h) \
    $(wildcard include/config/bcm/pci.h) \
    $(wildcard include/config/blk/dev/initrd.h) \
    $(wildcard include/config/dns/redirect/control.h) \
    $(wildcard include/config/arch/clocksource/data.h) \
    $(wildcard include/config/bcm/default/num/mbss.h) \
    $(wildcard include/config/zlib/inflate.h) \
    $(wildcard include/config/debug/ll.h) \
    $(wildcard include/config/thermal/of.h) \
    $(wildcard include/config/nf/nat/rtsp.h) \
    $(wildcard include/config/bcm/platform/impl.h) \
    $(wildcard include/config/net/sch/cbq.h) \
    $(wildcard include/config/bcm/kf/dm/create/backport.h) \
    $(wildcard include/config/arch/use/builtin/bswap.h) \
    $(wildcard include/config/cma/size/sel/mbytes.h) \
    $(wildcard include/config/bcm/board/impl.h) \
    $(wildcard include/config/bcm/kf/map.h) \
    $(wildcard include/config/stacktrace/support.h) \
    $(wildcard include/config/bcm/bpm/dynamic/expand/step/size.h) \
    $(wildcard include/config/bcm/glb/coherency.h) \
    $(wildcard include/config/arm.h) \
    $(wildcard include/config/crypto/kpp2.h) \
    $(wildcard include/config/tcp/cong/lia.h) \
    $(wildcard include/config/jffs2/fs.h) \
    $(wildcard include/config/arm/l1/cache/shift.h) \
    $(wildcard include/config/net/udp/tunnel.h) \
    $(wildcard include/config/refcount/full.h) \
    $(wildcard include/config/arm/patch/idiv.h) \
    $(wildcard include/config/cfg80211/require/signed/regdb.h) \
    $(wildcard include/config/bcm/bca/gpio/impl.h) \
    $(wildcard include/config/bcm/kf/kern/bug/fix.h) \
    $(wildcard include/config/bcm/wlan/dgasp.h) \
    $(wildcard include/config/bcm/pmc/impl.h) \
    $(wildcard include/config/mptcp.h) \
    $(wildcard include/config/crypto/drbg/hmac.h) \
    $(wildcard include/config/bcm/kf/spu.h) \
    $(wildcard include/config/bcm/wlan/impl.h) \
    $(wildcard include/config/generic/cpu/autoprobe.h) \
    $(wildcard include/config/standalone.h) \
    $(wildcard include/config/rational.h) \
    $(wildcard include/config/system/trusted/keyring.h) \
    $(wildcard include/config/watchdog/core.h) \
    $(wildcard include/config/generic/early/ioremap.h) \
    $(wildcard include/config/skip/fastpath.h) \
    $(wildcard include/config/have/ide.h) \
    $(wildcard include/config/block.h) \
    $(wildcard include/config/init/env/arg/limit.h) \
    $(wildcard include/config/debug/uart/virt.h) \
    $(wildcard include/config/bcm/common/clk.h) \
    $(wildcard include/config/nf/conntrack/pptp.h) \
    $(wildcard include/config/strict/kernel/rwx.h) \
    $(wildcard include/config/bcm/kf/usbnet.h) \
    $(wildcard include/config/bug.h) \
    $(wildcard include/config/arch/has/membarrier/sync/core.h) \
    $(wildcard include/config/spi.h) \
    $(wildcard include/config/nf/conntrack/irc.h) \
    $(wildcard include/config/of/irq.h) \
    $(wildcard include/config/libfdt.h) \
    $(wildcard include/config/bcm/kf/skb/ext.h) \
    $(wildcard include/config/ppp/deflate.h) \
    $(wildcard include/config/mptcp/pm/advanced.h) \
    $(wildcard include/config/dtc.h) \
    $(wildcard include/config/watchdog/handle/boot/enabled.h) \
    $(wildcard include/config/split/ptlock/cpus.h) \
    $(wildcard include/config/sbitmap.h) \
    $(wildcard include/config/sctp/cookie/hmac/md5.h) \
    $(wildcard include/config/cpu/cache/vipt.h) \
    $(wildcard include/config/bcm/wlaltbld.h) \
    $(wildcard include/config/nls.h) \
    $(wildcard include/config/spi/spidev.h) \
    $(wildcard include/config/bcm/kf/proto/ipsec.h) \
    $(wildcard include/config/pppoe.h) \
    $(wildcard include/config/xfrm/migrate.h) \
    $(wildcard include/config/nf/nat/ipv6.h) \
    $(wildcard include/config/irq/work.h) \
    $(wildcard include/config/pci/msi.h) \
    $(wildcard include/config/ip/advanced/router.h) \
    $(wildcard include/config/ip6/nf/iptables.h) \
    $(wildcard include/config/nl80211/testmode.h) \
    $(wildcard include/config/log/cpu/max/buf/shift.h) \
    $(wildcard include/config/tasks/rcu.h) \
    $(wildcard include/config/of/net.h) \
    $(wildcard include/config/arm/arch/timer.h) \
    $(wildcard include/config/tenda/xmesh/hb/enable.h) \
    $(wildcard include/config/bcm/mcast/impl.h) \
    $(wildcard include/config/portal/mac/white/list.h) \
    $(wildcard include/config/blk/mq/pci.h) \
    $(wildcard include/config/nls/iso8859/1.h) \
    $(wildcard include/config/crypto/workqueue.h) \
    $(wildcard include/config/nf/conntrack/procfs.h) \
    $(wildcard include/config/ppp/mppe.h) \
    $(wildcard include/config/bcm/kf/dpi.h) \
    $(wildcard include/config/netdevices.h) \
    $(wildcard include/config/net/key.h) \
    $(wildcard include/config/have/context/tracking.h) \
    $(wildcard include/config/arch/has/kcov.h) \
    $(wildcard include/config/cpu/tlb/v7.h) \
    $(wildcard include/config/eventfd.h) \
    $(wildcard include/config/bcm/kf/extra/debug.h) \
    $(wildcard include/config/ipv6/sit.h) \
    $(wildcard include/config/xfrm.h) \
    $(wildcard include/config/fpe/fastfpe.h) \
    $(wildcard include/config/bcm/cmdlist/spe.h) \
    $(wildcard include/config/bcm/kf/glb/coherency.h) \
    $(wildcard include/config/ipv6/multiple/tables.h) \
    $(wildcard include/config/net/cls/route4.h) \
    $(wildcard include/config/ip/nf/target/masquerade.h) \
    $(wildcard include/config/have/ebpf/jit.h) \
    $(wildcard include/config/proc/page/monitor.h) \
    $(wildcard include/config/mtd/spi/nor/use/4k/sectors.h) \
    $(wildcard include/config/bpf.h) \
    $(wildcard include/config/bcm/kf/arm/bcm963xx.h) \
    $(wildcard include/config/crypto/sha512.h) \
    $(wildcard include/config/mtd/of/parts.h) \
    $(wildcard include/config/crypto/null.h) \
    $(wildcard include/config/nf/defrag/ipv4.h) \
    $(wildcard include/config/might/have/pci.h) \
    $(wildcard include/config/have/arch/pfn/valid.h) \
    $(wildcard include/config/cpu/copy/v6.h) \
    $(wildcard include/config/accel/pptp.h) \
    $(wildcard include/config/bcm/kf/blog.h) \
    $(wildcard include/config/ipv6/route/info.h) \
    $(wildcard include/config/netfilter/advanced.h) \
    $(wildcard include/config/crypto/deflate.h) \
    $(wildcard include/config/generic/strnlen/user.h) \
    $(wildcard include/config/ipv6/router/pref.h) \
    $(wildcard include/config/jffs2/fs/debug.h) \
    $(wildcard include/config/crypto/jitterentropy.h) \
    $(wildcard include/config/bcm/kf/buzzz.h) \
    $(wildcard include/config/bcm/pktfwd/flctl.h) \
    $(wildcard include/config/crypto/gcm.h) \
    $(wildcard include/config/have/dynamic/ftrace.h) \
    $(wildcard include/config/magic/sysrq.h) \
    $(wildcard include/config/ipv6/sit/6rd.h) \
    $(wildcard include/config/pgtable/levels.h) \
    $(wildcard include/config/netfilter/xt/match/mark.h) \
    $(wildcard include/config/bcm/bca/pinctrl/impl.h) \
    $(wildcard include/config/bridge/ebt/blog.h) \
    $(wildcard include/config/arm/virt/ext.h) \
    $(wildcard include/config/sparse/irq.h) \
    $(wildcard include/config/ip/nf/mangle.h) \
    $(wildcard include/config/rcu/stall/common.h) \
    $(wildcard include/config/bridge/ebt/vlan.h) \
    $(wildcard include/config/pcieportbus.h) \
    $(wildcard include/config/debug/bugverbose.h) \
    $(wildcard include/config/ip/nf/filter.h) \
    $(wildcard include/config/bcm/bpm/dynamic/shrink/step/size.h) \
    $(wildcard include/config/may/use/devlink.h) \
    $(wildcard include/config/highmem.h) \
    $(wildcard include/config/ip6/nf/raw.h) \
    $(wildcard include/config/inet/tunnel.h) \
    $(wildcard include/config/generic/clockevents.h) \
    $(wildcard include/config/oid/registry.h) \
    $(wildcard include/config/bcm/kf/ubi.h) \
    $(wildcard include/config/rwsem/xchgadd/algorithm.h) \
    $(wildcard include/config/have/kernel/xz.h) \
    $(wildcard include/config/sctp/default/cookie/hmac/md5.h) \
    $(wildcard include/config/cpu/cp15/mmu.h) \
    $(wildcard include/config/serial/amba/pl011.h) \
    $(wildcard include/config/arch/supports/atomic/rmw.h) \
    $(wildcard include/config/portal/weixin/auth.h) \
    $(wildcard include/config/tenda/private.h) \
    $(wildcard include/config/net/ipgre.h) \
    $(wildcard include/config/bcm/wlan.h) \
    $(wildcard include/config/bcm/smtc/impl.h) \
    $(wildcard include/config/bridge/ebt/ip6.h) \
    $(wildcard include/config/serial/earlycon.h) \
    $(wildcard include/config/crypto/akcipher.h) \
    $(wildcard include/config/serial/amba/pl011/console.h) \
    $(wildcard include/config/nf/reject/ipv4.h) \
    $(wildcard include/config/arch/mmap/rnd/bits/max.h) \
    $(wildcard include/config/km/cb/size.h) \
    $(wildcard include/config/speed/test.h) \
    $(wildcard include/config/trace/skb/running/time.h) \
    $(wildcard include/config/tenda/wlan/prebe/limit.h) \
    $(wildcard include/config/trace/irqflags/support.h) \
    $(wildcard include/config/mfd/syscon.h) \
    $(wildcard include/config/sa/fastpath/learn/bypass/ptk/num.h) \
    $(wildcard include/config/crypto/ccm.h) \
    $(wildcard include/config/tcp/cong/advanced.h) \
    $(wildcard include/config/bcm/bca/led/impl.h) \
    $(wildcard include/config/bcm/kf/spi.h) \
    $(wildcard include/config/crypto/rng.h) \
    $(wildcard include/config/bp/phys/intf.h) \
    $(wildcard include/config/rd/gzip.h) \
    $(wildcard include/config/have/regs/and/stack/access/api.h) \
    $(wildcard include/config/nf/nat/pt.h) \
    $(wildcard include/config/tenda/sta/report.h) \
    $(wildcard include/config/gro/cells.h) \
    $(wildcard include/config/have/virt/cpu/accounting/gen.h) \
    $(wildcard include/config/pci/msi/irq/domain.h) \
    $(wildcard include/config/bcm/in/kernel.h) \
    $(wildcard include/config/inet/xfrm/mode/transport.h) \
    $(wildcard include/config/crypto/md5.h) \
    $(wildcard include/config/bcm/nvram.h) \
    $(wildcard include/config/sa/fastpath/ipc/sz.h) \
    $(wildcard include/config/debug/user.h) \
    $(wildcard include/config/bcm/wlan/dpdctl.h) \
    $(wildcard include/config/elfcore.h) \
    $(wildcard include/config/cpu/sw/domain/pan.h) \
    $(wildcard include/config/oabi/compat.h) \
    $(wildcard include/config/binfmt/elf.h) \
    $(wildcard include/config/bcm/963xx/pcie/hc.h) \
    $(wildcard include/config/have/perf/regs.h) \
    $(wildcard include/config/spi/bcm63xx/hsspi.h) \
    $(wildcard include/config/cpu/cp15.h) \
    $(wildcard include/config/hz/fixed.h) \
    $(wildcard include/config/km/kwdog.h) \
    $(wildcard include/config/bcm/kf/hwrng.h) \
    $(wildcard include/config/keys.h) \
    $(wildcard include/config/netfilter/xt/mark.h) \
    $(wildcard include/config/netfilter/xtables.h) \
    $(wildcard include/config/arch/has/phys/to/dma.h) \
    $(wildcard include/config/crypto/echainiv.h) \
    $(wildcard include/config/bcm/cleds/proc/driver.h) \
    $(wildcard include/config/sa/fastpath/nat/l2tp.h) \
    $(wildcard include/config/portal/control.h) \
    $(wildcard include/config/bcm/kf/sgs.h) \
    $(wildcard include/config/bcm/timer.h) \
    $(wildcard include/config/use/of.h) \
    $(wildcard include/config/magic/sysrq/default/enable.h) \
    $(wildcard include/config/hardirqs/sw/resend.h) \
    $(wildcard include/config/bridge/ebt/skbvlan.h) \
    $(wildcard include/config/jffs2/fs/writebuffer.h) \
    $(wildcard include/config/spi/master.h) \
    $(wildcard include/config/tenda/wlan/node/roaming.h) \
    $(wildcard include/config/net/act/gact.h) \
    $(wildcard include/config/arch/multi/v7.h) \
    $(wildcard include/config/bcm/bca/legacy/led/api.h) \
    $(wildcard include/config/thermal/emergency/poweroff/delay/ms.h) \
    $(wildcard include/config/console/loglevel/quiet.h) \
    $(wildcard include/config/cmdline/force.h) \
    $(wildcard include/config/crc16.h) \
    $(wildcard include/config/generic/calibrate/delay.h) \
    $(wildcard include/config/crypto/gf128mul.h) \
    $(wildcard include/config/hz/periodic.h) \
    $(wildcard include/config/net/cls.h) \
    $(wildcard include/config/bcm/vlan.h) \
    $(wildcard include/config/default/fullmesh.h) \
    $(wildcard include/config/anon/inodes.h) \
    $(wildcard include/config/flow/identify.h) \
    $(wildcard include/config/futex.h) \
    $(wildcard include/config/bcm/ca7/mpcore.h) \
    $(wildcard include/config/console/loglevel/default.h) \
    $(wildcard include/config/generic/sched/clock.h) \
    $(wildcard include/config/vmsplit/3g.h) \
    $(wildcard include/config/plugin/hostcc.h) \
    $(wildcard include/config/have/arch/bitreverse.h) \
    $(wildcard include/config/serial/core/console.h) \
    $(wildcard include/config/interface/isolate.h) \
    $(wildcard include/config/bcm/smtc.h) \
    $(wildcard include/config/ubifs/fs.h) \
    $(wildcard include/config/debug/ll/uart/pl01x.h) \
    $(wildcard include/config/nf/tables.h) \
    $(wildcard include/config/slub/debug.h) \
    $(wildcard include/config/bcm/ethwan.h) \
    $(wildcard include/config/net/sch/ingress.h) \
    $(wildcard include/config/pinctrl.h) \
    $(wildcard include/config/ipv6/ndisc/nodetype.h) \
    $(wildcard include/config/bcm/psci.h) \
    $(wildcard include/config/debug/uart/addr.h) \
    $(wildcard include/config/sysvipc.h) \
    $(wildcard include/config/sa/fastpath/brc/sz.h) \
    $(wildcard include/config/mtd/ubi/block.h) \
    $(wildcard include/config/have/debug/kmemleak.h) \
    $(wildcard include/config/printk/safe/log/buf/shift.h) \
    $(wildcard include/config/nf/conntrack/ftp.h) \
    $(wildcard include/config/modules.h) \
    $(wildcard include/config/cpu/has/asid.h) \
    $(wildcard include/config/bcm/kf/power/save.h) \
    $(wildcard include/config/mq/iosched/deadline.h) \
    $(wildcard include/config/bcm/map.h) \
    $(wildcard include/config/bcm/kf/extstats.h) \
    $(wildcard include/config/arch/hibernation/possible.h) \
    $(wildcard include/config/unix.h) \
    $(wildcard include/config/have/clk.h) \
    $(wildcard include/config/crypto/hash2.h) \
    $(wildcard include/config/thermal/gov/step/wise.h) \
    $(wildcard include/config/default/hostname.h) \
    $(wildcard include/config/srcu.h) \
    $(wildcard include/config/membarrier.h) \
    $(wildcard include/config/xps.h) \
    $(wildcard include/config/bcm/log.h) \
    $(wildcard include/config/inet/esp.h) \
    $(wildcard include/config/sgl/alloc.h) \
    $(wildcard include/config/flash/lock/support.h) \
    $(wildcard include/config/crypto/algapi.h) \
    $(wildcard include/config/wireless/wds.h) \
    $(wildcard include/config/generic/irq/show/level.h) \
    $(wildcard include/config/bridge.h) \
    $(wildcard include/config/net/ip/tunnel.h) \
    $(wildcard include/config/bcm/i2c/chip/impl.h) \
    $(wildcard include/config/mtd/cfi/i1.h) \
    $(wildcard include/config/nf/nat.h) \
    $(wildcard include/config/ubifs/fs/zlib.h) \
    $(wildcard include/config/cpu/idle.h) \
    $(wildcard include/config/crypto/hash.h) \
    $(wildcard include/config/efi/partition.h) \
    $(wildcard include/config/log/buf/shift.h) \
    $(wildcard include/config/hz/1000.h) \
    $(wildcard include/config/netfilter/xt/target/dscp.h) \
    $(wildcard include/config/extra/firmware.h) \
    $(wildcard include/config/ipv6/mroute.h) \
    $(wildcard include/config/crc32/sliceby8.h) \
    $(wildcard include/config/bcm/mcast.h) \
    $(wildcard include/config/cpu/rmap.h) \
    $(wildcard include/config/panic/on/oops.h) \
    $(wildcard include/config/bcm/cleds/proc/driver/impl.h) \
    $(wildcard include/config/blk/dev/loop.h) \
    $(wildcard include/config/bcm/mptcp.h) \
    $(wildcard include/config/have/optprobes.h) \
    $(wildcard include/config/spi/mem.h) \
    $(wildcard include/config/nf/nat/irc.h) \
    $(wildcard include/config/bcm/cmdlist.h) \
    $(wildcard include/config/auto/zreladdr.h) \
    $(wildcard include/config/cpu/pabrt/v7.h) \
    $(wildcard include/config/bcm/colorize/prints.h) \
    $(wildcard include/config/multiuser.h) \
    $(wildcard include/config/crypto/cbc.h) \
    $(wildcard include/config/blog/mcast.h) \
    $(wildcard include/config/squashfs/decomp/single.h) \
    $(wildcard include/config/clang/version.h) \
    $(wildcard include/config/crypto/rng/default.h) \
    $(wildcard include/config/net/cls/tcindex.h) \
    $(wildcard include/config/bcm/bca/gpio.h) \
    $(wildcard include/config/netfilter/family/arp.h) \
    $(wildcard include/config/arm/amba.h) \
    $(wildcard include/config/cpu/pm.h) \
    $(wildcard include/config/cfg80211/use/kernel/regdb/keys.h) \
    $(wildcard include/config/timer/of.h) \
    $(wildcard include/config/have/function/tracer.h) \
    $(wildcard include/config/cpu/isolation.h) \
    $(wildcard include/config/nf/nat/tftp.h) \
    $(wildcard include/config/netfilter/xt/match/multiport.h) \
    $(wildcard include/config/mtd/spi/nor.h) \
    $(wildcard include/config/cpu/cache/v7.h) \
    $(wildcard include/config/bcm/kf/vlan/dei.h) \
    $(wildcard include/config/nos/control/v2.h) \
    $(wildcard include/config/netfilter/xt/target/redirect.h) \
    $(wildcard include/config/crypto/manager2.h) \
    $(wildcard include/config/clz/tab.h) \
    $(wildcard include/config/tenda/wlan/repeater.h) \
    $(wildcard include/config/generic/pci/iomap.h) \
    $(wildcard include/config/netfilter/xt/target/log.h) \
    $(wildcard include/config/slub.h) \
    $(wildcard include/config/mtd/ubi.h) \
    $(wildcard include/config/i2c.h) \
    $(wildcard include/config/jffs2/zlib.h) \
    $(wildcard include/config/binfmt/script.h) \
    $(wildcard include/config/net/ipgre/broadcast.h) \
    $(wildcard include/config/cpu/abrt/ev7.h) \
    $(wildcard include/config/bcm/kf/mptcp.h) \
    $(wildcard include/config/tick/cpu/accounting.h) \
    $(wildcard include/config/crypto/ecb.h) \
    $(wildcard include/config/bcm/bootstate.h) \
    $(wildcard include/config/debug/fs.h) \
    $(wildcard include/config/have/kernel/lz4.h) \
    $(wildcard include/config/base/full.h) \
    $(wildcard include/config/zlib/deflate.h) \
    $(wildcard include/config/bcm/xhci/comp/quirk.h) \
    $(wildcard include/config/rseq.h) \
    $(wildcard include/config/gpio/sysfs.h) \
    $(wildcard include/config/fw/loader.h) \
    $(wildcard include/config/ip6/nf/nat.h) \
    $(wildcard include/config/bcm96xxx/wdt.h) \
    $(wildcard include/config/kallsyms.h) \
    $(wildcard include/config/common/clk.h) \
    $(wildcard include/config/stackprotector/strong.h) \
    $(wildcard include/config/pci.h) \
    $(wildcard include/config/crypto/xts.h) \
    $(wildcard include/config/pci/quirks.h) \
    $(wildcard include/config/net/core.h) \
    $(wildcard include/config/bcm/archer/impl.h) \
    $(wildcard include/config/bcm/arm/cpuidle.h) \
    $(wildcard include/config/uninline/spin/unlock.h) \
    $(wildcard include/config/bcm/kf/scsi/write/protect.h) \
    $(wildcard include/config/crypto/sha1.h) \
    $(wildcard include/config/arm/dma/mem/bufferable.h) \
    $(wildcard include/config/arch/want/general/hugetlb.h) \
    $(wildcard include/config/xz/dec.h) \
    $(wildcard include/config/dummy.h) \
    $(wildcard include/config/bridge/ebt/mark/t.h) \
    $(wildcard include/config/watchdog.h) \
    $(wildcard include/config/has/iomem.h) \
    $(wildcard include/config/nf/log/ipv6.h) \
    $(wildcard include/config/bcm/bpm/bulk/free.h) \
    $(wildcard include/config/crypto/rsa.h) \
    $(wildcard include/config/bcm/cmdlist/impl.h) \
    $(wildcard include/config/generic/irq/probe.h) \
    $(wildcard include/config/net/cls/ind.h) \
    $(wildcard include/config/crypto/acomp2.h) \
    $(wildcard include/config/mtd/map/bank/width/1.h) \
    $(wildcard include/config/net/sch/prio.h) \
    $(wildcard include/config/sched/hrtick.h) \
    $(wildcard include/config/sa/fastpath/fragment.h) \
    $(wildcard include/config/epoll.h) \
    $(wildcard include/config/crypto/lzo.h) \
    $(wildcard include/config/generic/irq/multi/handler.h) \
    $(wildcard include/config/partition/advanced.h) \
    $(wildcard include/config/have/net/dsa.h) \
    $(wildcard include/config/netfilter/xt/match/comment.h) \
    $(wildcard include/config/net.h) \
    $(wildcard include/config/bcm/pktflow/impl.h) \
    $(wildcard include/config/netfilter/xt/target/tcpmss.h) \
    $(wildcard include/config/netfilter/xt/match/dscp.h) \
    $(wildcard include/config/bcm/kf/mtd/oops.h) \
    $(wildcard include/config/netfilter/xt/match/conntrack.h) \
    $(wildcard include/config/vfpv3.h) \
    $(wildcard include/config/pinmux.h) \
    $(wildcard include/config/sa/fastpath/ipv6.h) \
    $(wildcard include/config/irq/domain/hierarchy.h) \
    $(wildcard include/config/mpilib.h) \
    $(wildcard include/config/packet.h) \
    $(wildcard include/config/xfrm/algo.h) \
    $(wildcard include/config/tenda/wlan/zip/image.h) \
    $(wildcard include/config/events/center.h) \
    $(wildcard include/config/have/clk/prepare.h) \
    $(wildcard include/config/crypto/akcipher2.h) \
    $(wildcard include/config/asymmetric/public/key/subtype.h) \
    $(wildcard include/config/nf/conntrack/tftp.h) \
    $(wildcard include/config/inet.h) \
    $(wildcard include/config/arm/module/plts.h) \
    $(wildcard include/config/netfilter/xt/match/addrtype.h) \
    $(wildcard include/config/prevent/firmware/build.h) \
    $(wildcard include/config/bcm/kf/nl80211/6g/band/support.h) \
    $(wildcard include/config/sa/fastpath.h) \
    $(wildcard include/config/http/redirect.h) \
    $(wildcard include/config/pci/domains.h) \
    $(wildcard include/config/bcm/max/ucast/flows.h) \
    $(wildcard include/config/net/cls/act.h) \
    $(wildcard include/config/mtd/partition/lock.h) \
    $(wildcard include/config/bridge/ebt/broute.h) \
    $(wildcard include/config/net/sch/sfq.h) \
    $(wildcard include/config/rtc/lib.h) \
    $(wildcard include/config/have/kprobes.h) \
    $(wildcard include/config/ip/route/classid.h) \
    $(wildcard include/config/crypto/aes.h) \
    $(wildcard include/config/gpiolib.h) \
    $(wildcard include/config/futex/pi.h) \
    $(wildcard include/config/bcm96756.h) \
    $(wildcard include/config/tenda/private/wlan.h) \
    $(wildcard include/config/arp/fence/control.h) \
    $(wildcard include/config/autofs/fs.h) \
    $(wildcard include/config/netfilter/xt/nat.h) \
    $(wildcard include/config/swp/emulate.h) \
    $(wildcard include/config/have/hardened/usercopy/allocator.h) \
    $(wildcard include/config/netfilter.h) \
    $(wildcard include/config/bridge/inhibit.h) \
    $(wildcard include/config/have/arch/kasan.h) \
    $(wildcard include/config/bcm/archer/wlan.h) \
    $(wildcard include/config/squashfs/embedded.h) \
    $(wildcard include/config/clone/backwards.h) \
    $(wildcard include/config/have/nmi.h) \
    $(wildcard include/config/blk/dev/ram/count.h) \
    $(wildcard include/config/dhd/param2/size.h) \
    $(wildcard include/config/ip/mroute.h) \
    $(wildcard include/config/inet/xfrm/mode/tunnel.h) \
    $(wildcard include/config/km/cb/staddr/for/modules.h) \
    $(wildcard include/config/preempt/rcu.h) \
    $(wildcard include/config/switch/bcm.h) \
    $(wildcard include/config/nf/nat/needed.h) \
    $(wildcard include/config/have/dynamic/ftrace/with/regs.h) \
    $(wildcard include/config/netfilter/xt/match/flowlabel.h) \
    $(wildcard include/config/bcm/map/impl.h) \
    $(wildcard include/config/printk/nmi.h) \
    $(wildcard include/config/net/flow/limit.h) \
    $(wildcard include/config/lockdep/support.h) \
    $(wildcard include/config/ip6/nf/target/masquerade.h) \
    $(wildcard include/config/bcm/max/fdb.h) \
    $(wildcard include/config/posix/mqueue.h) \
    $(wildcard include/config/netfilter/ingress.h) \
    $(wildcard include/config/bcm/enet.h) \
    $(wildcard include/config/default/mptcp/pm.h) \
    $(wildcard include/config/cpu/spectre.h) \
    $(wildcard include/config/bcm/pmc.h) \
    $(wildcard include/config/generic/strncpy/from/user.h) \
    $(wildcard include/config/mtd/blkdevs.h) \
    $(wildcard include/config/arm/has/sg/chain.h) \
    $(wildcard include/config/have/rseq.h) \
    $(wildcard include/config/netfilter/xt/target/netmap.h) \
    $(wildcard include/config/blog/l2tp.h) \
    $(wildcard include/config/of/kobj.h) \
    $(wildcard include/config/bcm/license.h) \
    $(wildcard include/config/netfilter/xt/match/sctp.h) \
    $(wildcard include/config/inet6/esp.h) \
    $(wildcard include/config/autofs4/fs.h) \
    $(wildcard include/config/nf/conntrack/rtsp.h) \
    $(wildcard include/config/ip6/nf/filter.h) \
    $(wildcard include/config/bcm/netfilter/regardless/drop/order.h) \
    $(wildcard include/config/system/data/verification.h) \
    $(wildcard include/config/need/dma/map/state.h) \
    $(wildcard include/config/bcm/kf/wl/hostapd.h) \
    $(wildcard include/config/tenda/scan/priority.h) \
    $(wildcard include/config/page/offset.h) \
    $(wildcard include/config/vendor/hnat/skip/pkts.h) \
    $(wildcard include/config/cpu/v7.h) \
    $(wildcard include/config/panic/timeout.h) \
    $(wildcard include/config/zboot/rom/bss.h) \
    $(wildcard include/config/arch/might/have/pc/parport.h) \
    $(wildcard include/config/cc/has/stackprotector/none.h) \
    $(wildcard include/config/nf/nat/masquerade/ipv4.h) \
    $(wildcard include/config/cfg80211/default/ps.h) \
    $(wildcard include/config/build/bin2c.h) \
    $(wildcard include/config/smp.h) \
    $(wildcard include/config/br/igmp/snoop.h) \
    $(wildcard include/config/tty.h) \
    $(wildcard include/config/have/kernel/gzip.h) \
    $(wildcard include/config/bcm/bootstate/impl.h) \
    $(wildcard include/config/netfilter/xt/match/mac.h) \
    $(wildcard include/config/generic/allocator.h) \
    $(wildcard include/config/l2tp.h) \
    $(wildcard include/config/tcp/cong/westwood.h) \
    $(wildcard include/config/bridge/ebt/wmm/mark.h) \
    $(wildcard include/config/libcrc32c.h) \
    $(wildcard include/config/arch/nr/gpio.h) \
    $(wildcard include/config/generic/bug.h) \
    $(wildcard include/config/crypto/sha256.h) \
    $(wildcard include/config/have/ftrace/mcount/record.h) \
    $(wildcard include/config/bcm/max/mcast/groups.h) \
    $(wildcard include/config/posix/timers.h) \
    $(wildcard include/config/bcm/log/impl.h) \
    $(wildcard include/config/mtd/ubi/gluebi.h) \
    $(wildcard include/config/bcm/kf/nf/regardless/drop.h) \
    $(wildcard include/config/devmem.h) \
    $(wildcard include/config/bcm/kf/nbuff.h) \
    $(wildcard include/config/bridge/ebt/ip.h) \
    $(wildcard include/config/iosched/noop.h) \
    $(wildcard include/config/have/uid16.h) \
    $(wildcard include/config/bcm/max/gem/ports.h) \
    $(wildcard include/config/neon.h) \
    $(wildcard include/config/bcm/i2c/bus/impl.h) \
    $(wildcard include/config/have/arm/smccc.h) \
    $(wildcard include/config/debug/kernel.h) \
    $(wildcard include/config/bcm/kf/atf.h) \
    $(wildcard include/config/bcm/archer/cpu/affinity.h) \
    $(wildcard include/config/multi/broad/filter/control.h) \
    $(wildcard include/config/localversion.h) \
    $(wildcard include/config/generic/irq/effective/aff/mask.h) \
    $(wildcard include/config/crypto.h) \
    $(wildcard include/config/default/mmap/min/addr.h) \
    $(wildcard include/config/system/trusted/keys.h) \
    $(wildcard include/config/ip/nf/iptables.h) \
    $(wildcard include/config/bcm/cma/rsvmem.h) \
    $(wildcard include/config/cmdline.h) \
    $(wildcard include/config/bcm/ext/switch/type.h) \
    $(wildcard include/config/bcm/cpu/arch/abi/name.h) \
    $(wildcard include/config/nf/dyndscp.h) \
    $(wildcard include/config/runtime/testing/menu.h) \
    $(wildcard include/config/default/cubic.h) \
    $(wildcard include/config/bridge/ebt/u32.h) \
    $(wildcard include/config/gpio/generic/platform.h) \
    $(wildcard include/config/bcm/wlan/16bit/station/chain/idx/support.h) \
    $(wildcard include/config/generic/msi/irq/domain.h) \
    $(wildcard include/config/strict/devmem.h) \
    $(wildcard include/config/generic/irq/show.h) \
    $(wildcard include/config/bcm/bpm/dynamic/avail/low/th.h) \
    $(wildcard include/config/bcm/cfe/xargs/early.h) \
    $(wildcard include/config/ipv6/optimistic/dad.h) \
    $(wildcard include/config/arch/has/elf/randomize.h) \
    $(wildcard include/config/panic/on/oops/value.h) \
    $(wildcard include/config/alignment/trap.h) \
    $(wildcard include/config/scsi/mod.h) \
    $(wildcard include/config/crypto/crc32c.h) \
    $(wildcard include/config/serial/core.h) \
    $(wildcard include/config/buildtime/extable/sort.h) \
    $(wildcard include/config/handle/domain/irq.h) \
    $(wildcard include/config/root/flashfs.h) \
    $(wildcard include/config/embedded.h) \
    $(wildcard include/config/have/kretprobes.h) \
    $(wildcard include/config/associative/array.h) \
    $(wildcard include/config/nf/defrag/ipv6.h) \
    $(wildcard include/config/ppp/filter.h) \
    $(wildcard include/config/rcu/need/segcblist.h) \
    $(wildcard include/config/mtd/rom.h) \
    $(wildcard include/config/has/dma.h) \
    $(wildcard include/config/nf/ct/proto/sctp.h) \
    $(wildcard include/config/bcm/bpm/dynamic/type/prcnt.h) \
    $(wildcard include/config/bcm/libs/impl.h) \
    $(wildcard include/config/nf/nat/pptp.h) \
    $(wildcard include/config/have/arch/thread/struct/whitelist.h) \
    $(wildcard include/config/bridge/ebt/ftos/t.h) \
    $(wildcard include/config/clkdev/lookup.h) \
    $(wildcard include/config/bcm/ingqos.h) \
    $(wildcard include/config/bcm/kf/netdev/ext.h) \
    $(wildcard include/config/squashfs/fragment/cache/size.h) \
    $(wildcard include/config/bridge/ebt/skiplog/t.h) \
    $(wildcard include/config/ipv6/tunnel.h) \
    $(wildcard include/config/network/isolate.h) \
    $(wildcard include/config/irq/domain.h) \
    $(wildcard include/config/uncompress/include.h) \
    $(wildcard include/config/bcm/max/host/dev.h) \
    $(wildcard include/config/arch/has/debug/virtual.h) \
    $(wildcard include/config/jffs2/rtime.h) \
    $(wildcard include/config/bcm/bpm/dynamic.h) \
    $(wildcard include/config/misc/filesystems.h) \
    $(wildcard include/config/arch/mmap/rnd/bits/min.h) \
    $(wildcard include/config/arm/l1/cache/shift/6.h) \
    $(wildcard include/config/might/have/cache/l2x0.h) \
    $(wildcard include/config/pppol2tp.h) \
    $(wildcard include/config/bcm/i2c/bus.h) \
    $(wildcard include/config/arch/supports/uprobes.h) \
    $(wildcard include/config/debug/ll/include.h) \
    $(wildcard include/config/bcm/kf/tcp/no/tsq.h) \
    $(wildcard include/config/nf/nat/h323.h) \
    $(wildcard include/config/of/gpio.h) \
    $(wildcard include/config/ip/nf/target/netmap.h) \
    $(wildcard include/config/dst/cache.h) \
    $(wildcard include/config/rcu/cpu/stall/timeout.h) \
    $(wildcard include/config/bcm/max/host/mac.h) \
    $(wildcard include/config/section/mismatch/warn/only.h) \
    $(wildcard include/config/net/sch/dsmark.h) \
    $(wildcard include/config/arm/cpu/suspend.h) \
    $(wildcard include/config/timer/probe.h) \
    $(wildcard include/config/bridge/ebt/mark.h) \
    $(wildcard include/config/pppoe/auth.h) \
    $(wildcard include/config/pcieaspm/default.h) \
    $(wildcard include/config/bridge/ebt/qos/map.h) \
    $(wildcard include/config/crypto/arc4.h) \
    $(wildcard include/config/bcm/ext/timer.h) \
    $(wildcard include/config/slhc.h) \
    $(wildcard include/config/have/smp.h) \
    $(wildcard include/config/bcm/otp.h) \
    $(wildcard include/config/bcm/bca/usb/impl.h) \
    $(wildcard include/config/bridge/ebt/reject.h) \
    $(wildcard include/config/crypto/manager.h) \
    $(wildcard include/config/net/sch/htb.h) \
    $(wildcard include/config/ppp/bsdcomp.h) \
    $(wildcard include/config/edac/support.h) \
    $(wildcard include/config/rt/mutexes.h) \
    $(wildcard include/config/lock/spin/on/owner.h) \
    $(wildcard include/config/netfilter/xt/target/mark.h) \
    $(wildcard include/config/pci/syscall.h) \
    $(wildcard include/config/slab/merge/default.h) \
    $(wildcard include/config/kernfs.h) \
    $(wildcard include/config/brcm/chip/rev.h) \
    $(wildcard include/config/ipv6/subtrees.h) \
    $(wildcard include/config/net/cls/fw.h) \
    $(wildcard include/config/expert.h) \
    $(wildcard include/config/cfg80211/crda/support.h) \
    $(wildcard include/config/wireless.h) \
    $(wildcard include/config/squashfs.h) \
    $(wildcard include/config/arch/multiplatform.h) \
    $(wildcard include/config/arch/has/strict/kernel/rwx.h) \
    $(wildcard include/config/lock/debugging/support.h) \
    $(wildcard include/config/net/sch/tbf.h) \
    $(wildcard include/config/pkcs7/message/parser.h) \
    $(wildcard include/config/perf/use/vmalloc.h) \
    $(wildcard include/config/platform/netlink.h) \
    $(wildcard include/config/tcp/cong/olia.h) \
    $(wildcard include/config/frame/warn.h) \
    $(wildcard include/config/bcm/kf/ppp.h) \
    $(wildcard include/config/arch/mmap/rnd/bits.h) \
    $(wildcard include/config/bcm/disable/nor/raw/partition.h) \
    $(wildcard include/config/bridge/ebt/vtag.h) \
    $(wildcard include/config/generic/hweight.h) \
    $(wildcard include/config/initramfs/source.h) \
    $(wildcard include/config/tenda/private/km.h) \
    $(wildcard include/config/lzo/compress.h) \
    $(wildcard include/config/crypto/seqiv.h) \
    $(wildcard include/config/bcm/def/nr/rx/dma/channels.h) \
    $(wildcard include/config/have/gcc/plugins.h) \
    $(wildcard include/config/bcm/pktfwd.h) \
    $(wildcard include/config/ipv6/gre.h) \
    $(wildcard include/config/ifb.h) \
    $(wildcard include/config/crypto/drbg.h) \
    $(wildcard include/config/pptp.h) \
    $(wildcard include/config/of/early/flattree.h) \
    $(wildcard include/config/debug/align/rodata.h) \
    $(wildcard include/config/bcm/nf/derived/conn.h) \
    $(wildcard include/config/has/ioport/map.h) \
    $(wildcard include/config/bcm/kf/fail/config/on/eof.h) \
    $(wildcard include/config/hz.h) \
    $(wildcard include/config/bcm/kf/suppress/debug.h) \
    $(wildcard include/config/netfilter/xt/match/u32.h) \
    $(wildcard include/config/squashfs/zlib.h) \
    $(wildcard include/config/arch/has/strict/module/rwx.h) \
    $(wildcard include/config/cc/is/gcc.h) \
    $(wildcard include/config/net/egress.h) \
    $(wildcard include/config/arm/patch/phys/virt.h) \
    $(wildcard include/config/inet/ah.h) \
    $(wildcard include/config/mtd/ubi/beb/limit.h) \
    $(wildcard include/config/default/iosched.h) \
    $(wildcard include/config/blog/localin/tcp.h) \
    $(wildcard include/config/have/perf/user/stack/dump.h) \
    $(wildcard include/config/nlattr.h) \
    $(wildcard include/config/tcp/cong/cubic.h) \
    $(wildcard include/config/nr/cpus.h) \
    $(wildcard include/config/have/exit/thread.h) \
    $(wildcard include/config/bcm/bca/legacy/led/api/impl.h) \
    $(wildcard include/config/sysfs.h) \
    $(wildcard include/config/bcm/bpm/dynamic/prcnt/max/buf.h) \
    $(wildcard include/config/arm/thumb.h) \
    $(wildcard include/config/asn1.h) \
    $(wildcard include/config/nf/log/common.h) \
    $(wildcard include/config/bridge/ebt/time.h) \
    $(wildcard include/config/netfilter/xt/match/limit.h) \
    $(wildcard include/config/bcm/cso.h) \
    $(wildcard include/config/net/key/migrate.h) \
    $(wildcard include/config/crypto/hash/info.h) \
    $(wildcard include/config/have/syscall/tracepoints.h) \
    $(wildcard include/config/tenda/wlan/ed/lowbound/avoid.h) \
    $(wildcard include/config/bcm/ubus/decode/remap.h) \
    $(wildcard include/config/mtd/complex/mappings.h) \
    $(wildcard include/config/cpu/32v7.h) \
    $(wildcard include/config/br/mld/snoop.h) \
    $(wildcard include/config/bcm/kf/optee.h) \
    $(wildcard include/config/cc/has/asm/goto.h) \
    $(wildcard include/config/msdos/partition.h) \
    $(wildcard include/config/bcm/hostapd.h) \
    $(wildcard include/config/have/oprofile.h) \
    $(wildcard include/config/have/generic/dma/coherent.h) \
    $(wildcard include/config/cpu/idle/gov/ladder.h) \
    $(wildcard include/config/arm/psci/fw.h) \
    $(wildcard include/config/arch/have/custom/gpio/h.h) \
    $(wildcard include/config/thermal.h) \
    $(wildcard include/config/old/sigaction.h) \
    $(wildcard include/config/bcm/wlan/remove/internal/debug.h) \
    $(wildcard include/config/ipv6/ra/netlink.h) \
    $(wildcard include/config/stackprotector.h) \
    $(wildcard include/config/cma/size/mbytes.h) \
    $(wildcard include/config/net/act/mirred.h) \
    $(wildcard include/config/have/arch/kgdb.h) \
    $(wildcard include/config/bcm/pktflow.h) \
    $(wildcard include/config/cpu/thumb/capable.h) \
    $(wildcard include/config/blk/debug/fs.h) \
    $(wildcard include/config/smp/on/up.h) \
    $(wildcard include/config/rps.h) \
    $(wildcard include/config/hw/random/iproc/rng200.h) \
    $(wildcard include/config/legacy/pty/count.h) \
    $(wildcard include/config/mtd/map/bank/width/2.h) \
    $(wildcard include/config/generic/idle/poll/setup.h) \
    $(wildcard include/config/ip/multicast.h) \
    $(wildcard include/config/bcm/chipinfo/impl.h) \
    $(wildcard include/config/squashfs/xz.h) \
    $(wildcard include/config/cpu/32v6k.h) \
    $(wildcard include/config/default/security.h) \
    $(wildcard include/config/tick/oneshot.h) \
    $(wildcard include/config/crypto/ctr.h) \
    $(wildcard include/config/mptcp/fullmesh.h) \
    $(wildcard include/config/udp/fragment/cache.h) \
    $(wildcard include/config/blog/ipv6.h) \
    $(wildcard include/config/hw/random.h) \
    $(wildcard include/config/mutex/spin/on/owner.h) \
    $(wildcard include/config/early/printk.h) \
    $(wildcard include/config/default/noop.h) \
    $(wildcard include/config/nf/nat/ipv4.h) \
    $(wildcard include/config/have/function/graph/tracer.h) \
    $(wildcard include/config/bcm/common/clk/impl.h) \
    $(wildcard include/config/tree/srcu.h) \
    $(wildcard include/config/crypto/null2.h) \
    $(wildcard include/config/debug/uart/phys.h) \
    $(wildcard include/config/netfilter/hash/size/km.h) \
    $(wildcard include/config/ip/sctp.h) \
    $(wildcard include/config/base/small.h) \
    $(wildcard include/config/crypto/blkcipher2.h) \
    $(wildcard include/config/blog.h) \
    $(wildcard include/config/bcm/kf/netfilter.h) \
    $(wildcard include/config/bcm/ethtool.h) \
    $(wildcard include/config/bcm/kf/misc/backports.h) \
    $(wildcard include/config/bcm/proc/cpu/affinity/hint.h) \
    $(wildcard include/config/sa/fastpath/nat.h) \
    $(wildcard include/config/proc/fs.h) \
    $(wildcard include/config/mtd/block.h) \
    $(wildcard include/config/bcm/archer/gso.h) \
    $(wildcard include/config/bcm/bpm/impl.h) \
    $(wildcard include/config/irq/forced/threading.h) \
    $(wildcard include/config/edac/atomic/scrub.h) \
    $(wildcard include/config/tenda/private/bsp.h) \
    $(wildcard include/config/bcm/cperouter.h) \
    $(wildcard include/config/flatmem.h) \
    $(wildcard include/config/bcm/kf/pci/reset/domain/nr.h) \
    $(wildcard include/config/harden/branch/predictor.h) \
    $(wildcard include/config/bcm/kf/arm/kasan.h) \
    $(wildcard include/config/bcm/kf/netfilter/sip.h) \
    $(wildcard include/config/ikconfig.h) \
    $(wildcard include/config/generic/irq/migration.h) \
    $(wildcard include/config/tenda/game/speedup.h) \
    $(wildcard include/config/arch/has/fortify/source.h) \
    $(wildcard include/config/gcc/version.h) \
    $(wildcard include/config/sysctl.h) \
    $(wildcard include/config/bcm/platform.h) \
    $(wildcard include/config/arch/has/gcov/profile/all.h) \
    $(wildcard include/config/have/c/recordmcount.h) \
    $(wildcard include/config/generic/msi/irq.h) \
    $(wildcard include/config/have/arch/tracehook.h) \
    $(wildcard include/config/ldm/partition.h) \
    $(wildcard include/config/pci/domains/generic.h) \
    $(wildcard include/config/xfrm/user.h) \
    $(wildcard include/config/bcm/skb/free/thread.h) \
    $(wildcard include/config/tcp/cong/bic.h) \
    $(wildcard include/config/have/perf/events.h) \
    $(wildcard include/config/super/user.h) \
    $(wildcard include/config/ppp/async.h) \
    $(wildcard include/config/tenda/follow/nettype.h) \
    $(wildcard include/config/no/bootmem.h) \
    $(wildcard include/config/thermal/default/gov/step/wise.h) \
    $(wildcard include/config/bcm/pci/msi.h) \
    $(wildcard include/config/sys/supports/apm/emulation.h) \
    $(wildcard include/config/cma/areas.h) \
    $(wildcard include/config/bcm/ingqos/impl.h) \
    $(wildcard include/config/pcieaspm.h) \
    $(wildcard include/config/arm/gic/max/nr.h) \
    $(wildcard include/config/tenda/wlan/wl/debug/mini.h) \
    $(wildcard include/config/bcm/pcie/hcd/impl.h) \
    $(wildcard include/config/bcm/kf/cpu/affinity/hint.h) \
    $(wildcard include/config/ipv6/mroute/multiple/tables.h) \
    $(wildcard include/config/blk/dev.h) \
    $(wildcard include/config/km/debug.h) \
    $(wildcard include/config/bcm/kf/l2cache/optimization.h) \
    $(wildcard include/config/bcm/kf/arm64/bcm963xx.h) \
    $(wildcard include/config/of/flattree.h) \
    $(wildcard include/config/gpio/generic.h) \
    $(wildcard include/config/tracing/support.h) \
    $(wildcard include/config/unix98/ptys.h) \
    $(wildcard include/config/net/rx/busy/poll.h) \
    $(wildcard include/config/net/sched.h) \
    $(wildcard include/config/bcm/board.h) \
    $(wildcard include/config/bcm/def/nr/tx/dma/channels.h) \
    $(wildcard include/config/irqchip.h) \
    $(wildcard include/config/ppp.h) \
    $(wildcard include/config/have/kernel/lzo.h) \
    $(wildcard include/config/crypto/ghash.h) \
    $(wildcard include/config/os/identify.h) \
    $(wildcard include/config/nf/nat/ftp.h) \
    $(wildcard include/config/board/params/phys.h) \
    $(wildcard include/config/ikconfig/proc.h) \
    $(wildcard include/config/elf/core.h) \
    $(wildcard include/config/bcm/license/impl.h) \
    $(wildcard include/config/km/nf/conntrack.h) \
    $(wildcard include/config/bcm/pcie/vcd.h) \
    $(wildcard include/config/bcm/kf/misc/makefile.h) \
    $(wildcard include/config/dma/cma.h) \
    $(wildcard include/config/flat/node/mem/map.h) \
    $(wildcard include/config/mq/iosched/kyber.h) \
    $(wildcard include/config/cc/optimize/for/performance.h) \
    $(wildcard include/config/blk/dev/ram.h) \
    $(wildcard include/config/bcm/kf/ndi.h) \
    $(wildcard include/config/netfilter/xt/match/state.h) \
    $(wildcard include/config/bcm/bpm/dynamic/prcnt/init/buf.h) \
    $(wildcard include/config/ddos/control.h) \
    $(wildcard include/config/posix/mqueue/sysctl.h) \
    $(wildcard include/config/preempt.h) \
    $(wildcard include/config/portal/url/white/list.h) \
    $(wildcard include/config/arch/optional/kernel/rwx.h) \
    $(wildcard include/config/mandatory/file/locking.h) \
    $(wildcard include/config/arch/has/tick/broadcast.h) \
    $(wildcard include/config/sysvipc/sysctl.h) \
    $(wildcard include/config/of/address.h) \
    $(wildcard include/config/decompress/gzip.h) \
    $(wildcard include/config/virtio/menu.h) \
    $(wildcard include/config/secure.h) \
    $(wildcard include/config/bcm/fhw.h) \
    $(wildcard include/config/i2c/chardev.h) \
    $(wildcard include/config/llc.h) \
    $(wildcard include/config/regmap/mmio.h) \
    $(wildcard include/config/generic/clockevents/broadcast.h) \
    $(wildcard include/config/vfs/lock/support.h) \
    $(wildcard include/config/arch/use/cmpxchg/lockref.h) \
    $(wildcard include/config/regmap.h) \
    $(wildcard include/config/have/mod/arch/specific.h) \
    $(wildcard include/config/bcm/nvram/impl.h) \
    $(wildcard include/config/strict/module/rwx.h) \
    $(wildcard include/config/net/act/police.h) \
    $(wildcard include/config/auto/discover.h) \
    $(wildcard include/config/new/leds.h) \
    $(wildcard include/config/online/ip/l2.h) \
    $(wildcard include/config/dhd/param3/size.h) \
    $(wildcard include/config/crc/ccitt.h) \
    $(wildcard include/config/bcm/libs.h) \
    $(wildcard include/config/netfilter/netlink.h) \
    $(wildcard include/config/module/unload.h) \
    $(wildcard include/config/preempt/count.h) \
    $(wildcard include/config/cma.h) \
    $(wildcard include/config/rwsem/spin/on/owner.h) \
    $(wildcard include/config/bitreverse.h) \
    $(wildcard include/config/sa/fastpath/l2.h) \
    $(wildcard include/config/x509/certificate/parser.h) \
    $(wildcard include/config/blk/dev/ram/size.h) \
    $(wildcard include/config/crypto/blkcipher.h) \
    $(wildcard include/config/bcm/max/mcast/clients/per/group.h) \
    $(wildcard include/config/bcm/ext/timer/impl.h) \
    $(wildcard include/config/nf/conntrack.h) \
    $(wildcard include/config/file/locking.h) \
    $(wildcard include/config/isolate.h) \
    $(wildcard include/config/bcm/bpm.h) \
    $(wildcard include/config/dhd/param1/size.h) \
    $(wildcard include/config/bcm/max/mcast/clients.h) \
    $(wildcard include/config/of.h) \
    $(wildcard include/config/bcm/kf/mtd/bcm963xx.h) \
    $(wildcard include/config/ip/nf/target/reject.h) \
    $(wildcard include/config/board/zreladdr.h) \
    $(wildcard include/config/leds/class.h) \
    $(wildcard include/config/kallsyms/base/relative.h) \
    $(wildcard include/config/arm/psci.h) \
    $(wildcard include/config/mtd/map/bank/width/4.h) \
    $(wildcard include/config/dcache/word/access.h) \
    $(wildcard include/config/cpu/little/endian.h) \
    $(wildcard include/config/message/loglevel/default.h) \
    $(wildcard include/config/cma/alignment.h) \
    $(wildcard include/config/nls/default.h) \
    $(wildcard include/config/nf/ct/proto/gre.h) \
    $(wildcard include/config/have/arm/arch/timer.h) \
    $(wildcard include/config/crypto/aead2.h) \
    $(wildcard include/config/nf/nat/masquerade/ipv6.h) \
    $(wildcard include/config/bcm/kf/char/sysrq.h) \
    $(wildcard include/config/crypto/algapi2.h) \
    $(wildcard include/config/ubifs/fs/lzo.h) \
    $(wildcard include/config/zboot/rom/text.h) \
    $(wildcard include/config/bcm/kf/mtd/bcmnand.h) \
    $(wildcard include/config/have/memblock.h) \
    $(wildcard include/config/have/efficient/unaligned/access.h) \
    $(wildcard include/config/proc/sysctl.h) \
    $(wildcard include/config/mmu.h) \
    $(wildcard include/config/mtd/m25p80.h) \
    $(wildcard include/config/bcm/kf/br/hooks.h) \
    $(wildcard include/config/kuser/helpers.h) \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../boot_rsvdmem.dtsi \
    $(wildcard include/config/optee.h) \
    $(wildcard include/config/arm64.h) \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_cortexA7_quad.dtsi \
  scripts/dtc/include-prefixes/dt-bindings/interrupt-controller/arm-gic.h \
  scripts/dtc/include-prefixes/dt-bindings/interrupt-controller/irq.h \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../bcm_rsvdmem.dtsi \
    $(wildcard include/config/bcm/adsl.h) \
    $(wildcard include/config/bcm/rdpa.h) \
    $(wildcard include/config/bcm/mpm.h) \
    $(wildcard include/config/bcm/dhd/runner.h) \
    $(wildcard include/config/bcm/pon/xrdp.h) \
    $(wildcard include/config/bcm/jumbo/frame.h) \
    $(wildcard include/config/bcm/fpm/pool/num.h) \
    $(wildcard include/config/bcm/rdpa/mcast.h) \
    $(wildcard include/config/brcm/qemu.h) \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_clocks.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/memc.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcmbca_memc_dt_bindings.h \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_nand7_1.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_sdhci.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_hs_uart.dtsi \
    $(wildcard include/config/bcm963138.h) \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_rng200.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_pmc_3_2.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_boot_state_v2.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_usb_ctrl.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_usb_xhci.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_usb_ehci.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_usb_ohci.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_i2c_bus.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_arm_uart.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_timer.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_wdt.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_sotp.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_bca_pinctrl.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/6756-pinctrl.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_bca_gpio.dtsi \
  scripts/dtc/include-prefixes/dt-bindings/gpio/gpio.h \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_bca_extintr.dtsi \
  scripts/dtc/include-prefixes/../../../bcmdrivers/opensource/include/bcm963xx/bcm_bca_extintr_dt_bindings.h \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_hsspi.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_spinand.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_spinor.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_cled_ctrl.dtsi \
  scripts/dtc/include-prefixes/../../../bcmdrivers/opensource/include/bcm963xx/bcm_bca_leds_dt_bindings.h \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/6756_leds.dtsi \
  /home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/../ip/bcm_pcie_core.dtsi \

/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dtb: $(deps_/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dtb)

$(deps_/home/startlab/Broadcom/HomeCoverage0524/bsp/kernel/bcm_v5_04L_02p1_4.19/dts/6756/96757REF2T.dtb):
